# Clear Vault-managed secret values from services/*/.env (and infra redis .env).
# Non-secret config (Kafka, outbox mode, ports, ...) is preserved.
# Secrets are injected at runtime via .env.vault generated by sync-env-from-vault.ps1.
#
# Usage:
#   .\infrastructure\vault\scripts\strip-vault-secrets-from-env.ps1

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Resolve-Path (Join-Path (Split-Path -Parent $ScriptDir) "..\..")

function Set-EnvKeyEmpty {
  param([string]$FilePath, [string]$Key)
  if (-not (Test-Path $FilePath)) { return }
  $lines = Get-Content $FilePath
  $found = $false
  $newLines = foreach ($line in $lines) {
    if ($line -match "^\s*$([regex]::Escape($Key))\s*=") {
      $found = $true
      "$Key="
    } else {
      $line
    }
  }
  if (-not $found) {
    $newLines += "$Key="
  }
  Set-Content -Path $FilePath -Value $newLines -Encoding utf8NoBOM
}

function Set-UrlVaultSyncPlaceholder {
  param([string]$FilePath, [string]$SchemePrefix, [string]$UserPrefix)
  if (-not (Test-Path $FilePath)) { return }
  $content = Get-Content $FilePath -Raw
  $pattern = "($([regex]::Escape($SchemePrefix)))[^@]+@"
  $replacement = "`${1}${UserPrefix}VAULT_SYNC@"
  $newContent = [regex]::Replace($content, $pattern, $replacement)
  if ($newContent -ne $content) {
    Set-Content -Path $FilePath -Value $newContent.TrimEnd() -Encoding utf8NoBOM -NoNewline
    Add-Content -Path $FilePath -Value "" -Encoding utf8NoBOM
  }
}

$services = Join-Path $RepoRoot "services"
$authEnv = Join-Path $services "auth-service\.env"
$userEnv = Join-Path $services "user-service\.env"
$wsEnv = Join-Path $services "workspace-service\.env"
$taskEnv = Join-Path $services "task-service\.env"
$notifEnv = Join-Path $services "notification-service\.env"
$redisEnv = Join-Path $RepoRoot "infrastructure\redis\.env"

foreach ($f in @($authEnv, $userEnv, $wsEnv, $taskEnv, $notifEnv, $redisEnv)) {
  $example = "$f.example"
  if (-not (Test-Path $f) -and (Test-Path $example)) {
    Copy-Item $example $f
    Write-Host "Created $f from .env.example"
  }
}

# Scalar secrets — empty in .env
foreach ($f in @($authEnv, $notifEnv)) { Set-EnvKeyEmpty $f "JWT_SECRET" }
foreach ($f in @($authEnv, $userEnv, $wsEnv, $taskEnv, $notifEnv)) {
  Set-EnvKeyEmpty $f "SERVICE_JWT_SECRET"
  Set-EnvKeyEmpty $f "METRICS_AUTH_TOKEN"
}
Set-EnvKeyEmpty $authEnv "REDIS_PASSWORD"
Set-EnvKeyEmpty $notifEnv "REDIS_PASSWORD"
Set-EnvKeyEmpty $userEnv "AZURE_STORAGE_CONNECTION_STRING"
Set-EnvKeyEmpty $taskEnv "AZURE_STORAGE_CONNECTION_STRING"
Set-EnvKeyEmpty $redisEnv "REDIS_PASSWORD"

# URL credentials — VAULT_SYNC placeholder
foreach ($f in @($authEnv, $userEnv, $wsEnv)) {
  Set-UrlVaultSyncPlaceholder $f "postgresql://" "postgres:"
}
foreach ($f in @($taskEnv, $notifEnv)) {
  Set-UrlVaultSyncPlaceholder $f "mongodb://" "admin:"
}

Write-Host "Cleared Vault-managed values in .env files (secrets belong in Vault → .env.vault via sync)."
