# Pull shared secrets from Vault into services/*/.env.vault (gitignored).
# services/*/.env keeps non-secret config only — run strip-vault-secrets-from-env.ps1 first.
#
# Usage:
#   .\infrastructure\vault\scripts\sync-env-from-vault.ps1

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$VaultDir = Split-Path -Parent $ScriptDir
$RepoRoot = Resolve-Path (Join-Path $VaultDir "..\..")

function Load-DotEnv {
  param([string]$Path)
  if (-not (Test-Path $Path)) { return @{} }
  $vars = @{}
  Get-Content $Path | ForEach-Object {
    $line = $_.Trim()
    if ($line -eq "" -or $line.StartsWith("#")) { return }
    $idx = $line.IndexOf("=")
    if ($idx -lt 1) { return }
    $key = $line.Substring(0, $idx).Trim()
    $val = $line.Substring($idx + 1).Trim()
    $vars[$key] = $val
  }
  return $vars
}

$defaults = Load-DotEnv (Join-Path $VaultDir ".env.example")
$overrides = Load-DotEnv (Join-Path $VaultDir ".env")

function Get-ConfigValue {
  param([string]$Key, [string]$Default = "")
  if ($overrides.ContainsKey($Key) -and $overrides[$Key] -ne "") { return $overrides[$Key] }
  if ($defaults.ContainsKey($Key)) { return $defaults[$Key] }
  return $Default
}

$vaultAddr = $env:VAULT_ADDR
if (-not $vaultAddr) { $vaultAddr = Get-ConfigValue "VAULT_ADDR" "http://127.0.0.1:8200" }

$token = $env:VAULT_TOKEN
if (-not $token) { $token = Get-ConfigValue "VAULT_DEV_ROOT_TOKEN" "collabspace-dev-root" }

$kvPath = Get-ConfigValue "VAULT_KV_PATH" "collabspace/dev"
$uri = "$vaultAddr/v1/secret/data/$kvPath"
$headers = @{ "X-Vault-Token" = $token }

Write-Host "Reading secret/data/$kvPath from $vaultAddr ..."
$response = Invoke-RestMethod -Method Get -Uri $uri -Headers $headers
$secrets = $response.data.data

$jwt = $secrets.jwt_secret
$serviceJwt = $secrets.service_jwt_secret
$pgPass = $secrets.postgres_password
$mongoUser = $secrets.mongo_username
$mongoPass = $secrets.mongo_password
$redisPass = $secrets.redis_password
$rmqUser = $secrets.rabbitmq_username
$rmqPass = $secrets.rabbitmq_password
$metrics = $secrets.metrics_auth_token
$azure = $secrets.azure_storage_connection_string
$brevo = $secrets.brevo_api_key

function Write-VaultEnvFile {
  param([string]$FilePath, [hashtable]$Entries)
  $lines = @("# Generated by sync-env-from-vault.ps1 — DO NOT COMMIT")
  foreach ($key in ($Entries.Keys | Sort-Object)) {
    $val = $Entries[$key]
    if ($null -ne $val -and "$val".Length -gt 0) {
      if ("$val" -match '[;\s#]') {
        $lines += "$key=`"$val`""
      } else {
        $lines += "$key=$val"
      }
    }
  }
  Set-Content -Path $FilePath -Value ($lines -join "`n") -Encoding utf8NoBOM
}

function Read-EnvValue {
  param([string]$FilePath, [string]$Key, [string]$Default)
  if (-not (Test-Path $FilePath)) { return $Default }
  foreach ($line in Get-Content $FilePath) {
    if ($line -match "^\s*$([regex]::Escape($Key))\s*=(.*)$") {
      $v = $Matches[1].Trim()
      if ($v.StartsWith('"') -and $v.EndsWith('"')) { $v = $v.Substring(1, $v.Length - 2) }
      if ($v.Length -gt 0 -and $v -ne "VAULT_SYNC") { return $v }
    }
  }
  return $Default
}

function Build-PostgresUrl {
  param([string]$ConfigEnv, [string]$DbName)
  $raw = Read-EnvValue $ConfigEnv "DATABASE_URL" "postgresql://postgres:VAULT_SYNC@postgres:5432/${DbName}?schema=public"
  $userEnc = [uri]::EscapeDataString("postgres")
  $passEnc = [uri]::EscapeDataString($pgPass)
  return [regex]::Replace($raw, '(postgresql://)[^@]+@', "`${1}${userEnc}:${passEnc}@")
}

function Build-MongoUrl {
  param([string]$ConfigEnv, [string]$DbName)
  $raw = Read-EnvValue $ConfigEnv "MONGO_URI" "mongodb://${mongoUser}:VAULT_SYNC@mongo:27017/${DbName}?authSource=admin"
  $userEnc = [uri]::EscapeDataString($mongoUser)
  $passEnc = [uri]::EscapeDataString($mongoPass)
  return [regex]::Replace($raw, '(mongodb://)[^@]+@', "`${1}${userEnc}:${passEnc}@")
}

function Build-RabbitUrl {
  param([string]$ConfigEnv)
  $raw = Read-EnvValue $ConfigEnv "RABBITMQ_URL" "amqp://${rmqUser}:VAULT_SYNC@rabbitmq:5672/collabspace"
  $userEnc = [uri]::EscapeDataString($rmqUser)
  $passEnc = [uri]::EscapeDataString($rmqPass)
  return [regex]::Replace($raw, '(amqp://)[^@]+@', "`${1}${userEnc}:${passEnc}@")
}

$services = Join-Path $RepoRoot "services"
$authConfig = Join-Path $services "auth-service\.env"
$userConfig = Join-Path $services "user-service\.env"
$wsConfig = Join-Path $services "workspace-service\.env"
$taskConfig = Join-Path $services "task-service\.env"
$notifConfig = Join-Path $services "notification-service\.env"

$authVault = Join-Path $services "auth-service\.env.vault"
$userVault = Join-Path $services "user-service\.env.vault"
$wsVault = Join-Path $services "workspace-service\.env.vault"
$taskVault = Join-Path $services "task-service\.env.vault"
$notifVault = Join-Path $services "notification-service\.env.vault"
$rabbitVault = Join-Path $RepoRoot "infrastructure\rabbitmq\.env.vault"
$redisVault = Join-Path $RepoRoot "infrastructure\redis\.env.vault"

$authEntries = @{
  JWT_SECRET = $jwt
  SERVICE_JWT_SECRET = $serviceJwt
  DATABASE_URL = (Build-PostgresUrl $authConfig "collabspace_auth")
  RABBITMQ_URL = (Build-RabbitUrl $authConfig)
  REDIS_PASSWORD = $redisPass
}
if ($metrics) { $authEntries["METRICS_AUTH_TOKEN"] = $metrics }
if ($brevo) { $authEntries["BREVO_API_KEY"] = $brevo }
Write-VaultEnvFile $authVault $authEntries

$userEntries = @{
  SERVICE_JWT_SECRET = $serviceJwt
  DATABASE_URL = (Build-PostgresUrl $userConfig "collabspace_user")
  RABBITMQ_URL = (Build-RabbitUrl $userConfig)
}
if ($metrics) { $userEntries["METRICS_AUTH_TOKEN"] = $metrics }
if ($azure) { $userEntries["AZURE_STORAGE_CONNECTION_STRING"] = $azure }
Write-VaultEnvFile $userVault $userEntries

$wsEntries = @{
  SERVICE_JWT_SECRET = $serviceJwt
  DATABASE_URL = (Build-PostgresUrl $wsConfig "collabspace_workspace")
}
if ($metrics) { $wsEntries["METRICS_AUTH_TOKEN"] = $metrics }
Write-VaultEnvFile $wsVault $wsEntries

$taskEntries = @{
  SERVICE_JWT_SECRET = $serviceJwt
  MONGO_URI = (Build-MongoUrl $taskConfig "collabspace_task")
  RABBITMQ_URL = (Build-RabbitUrl $taskConfig)
}
if ($metrics) { $taskEntries["METRICS_AUTH_TOKEN"] = $metrics }
if ($azure) { $taskEntries["AZURE_STORAGE_CONNECTION_STRING"] = $azure }
Write-VaultEnvFile $taskVault $taskEntries

$notifEntries = @{
  JWT_SECRET = $jwt
  SERVICE_JWT_SECRET = $serviceJwt
  MONGO_URI = (Build-MongoUrl $notifConfig "collabspace_notification")
  RABBITMQ_URL = (Build-RabbitUrl $notifConfig)
  REDIS_PASSWORD = $redisPass
}
if ($metrics) { $notifEntries["METRICS_AUTH_TOKEN"] = $metrics }
Write-VaultEnvFile $notifVault $notifEntries

Write-VaultEnvFile $rabbitVault @{
  RABBITMQ_DEFAULT_USER = $rmqUser
  RABBITMQ_DEFAULT_PASS = $rmqPass
  RABBITMQ_DEFAULT_VHOST = "collabspace"
}

Write-VaultEnvFile $redisVault @{ REDIS_PASSWORD = $redisPass }

$redisConf = Join-Path $RepoRoot "infrastructure\redis\redis.conf"
if ((Test-Path $redisConf) -and $redisPass) {
  $conf = Get-Content $redisConf -Raw
  $newConf = [regex]::Replace($conf, '(?m)^requirepass .*$', "requirepass $redisPass")
  if ($newConf -ne $conf) {
    Set-Content -Path $redisConf -Value $newConf.TrimEnd() -Encoding utf8NoBOM -NoNewline
    Add-Content -Path $redisConf -Value "" -Encoding utf8NoBOM
  }
}

Write-Host "Wrote Vault secrets to .env.vault files (services + rabbitmq + redis)."
Write-Host "Docker Compose loads .env + .env.vault — keep .env secret fields empty."
