{{- if .Values.global.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "collabspace.namespace" . }}
  labels:
    {{- include "collabspace.labels" . | nindent 4 }}
    app.kubernetes.io/name: collabspace
{{- end }}
