export const GRAPHILE_WORKER_OPTIONS = Symbol('GRAPHILE_WORKER_OPTIONS');
export const GRAPHILE_WORKER_UTILS_TOKEN = Symbol(
  'GRAPHILE_WORKER_UTILS_TOKEN',
);
export const GRAPHILE_WORKER_TASK_LIST = Symbol('GRAPHILE_WORKER_TASK_LIST');
