services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - ../logging/esdata:/usr/share/elasticsearch/data
    networks:
      - collabspace-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.2
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ../logging/logstash-config.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - collabspace-network
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - collabspace-network
    depends_on:
      - elasticsearch

volumes:
  esdata: