{{- $root := . -}}
{{- $ns := include "collabspace.namespace" . -}}
{{- range $name, $app := .Values.apps }}
{{- if $app.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-config
  namespace: {{ $ns }}
  labels:
    {{- include "collabspace.appLabels" (dict "appName" $name "root" $root) | nindent 4 }}
data:
  NODE_ENV: "production"
  PORT: {{ $app.httpPort | quote }}
  LOG_LEVEL: "info"
  TRACING_ENABLED: {{ if $root.Values.observability.jaeger.enabled }}"true"{{ else }}"false"{{ end }}
  SWAGGER_UI_PATH: {{ include "collabspace.swaggerUiPath" (dict "appName" $name "app" $app) | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318/v1/traces"
  JAEGER_AGENT_HOST: "jaeger"
  {{- if eq $name "auth-service" }}
  DATABASE_SCHEMA: "public"
  DATABASE_SSL: "false"
  DATABASE_SYNCHRONIZE: "false"
  {{- end }}
  {{- if eq $name "user-service" }}
  DATABASE_SCHEMA: "public"
  DATABASE_SSL: "false"
  DATABASE_SYNCHRONIZE: "false"
  {{- end }}
  {{- if eq $name "workspace-service" }}
  DATABASE_SCHEMA: "public"
  DATABASE_LOGGING: "false"
  {{- end }}
  {{- if eq $name "task-service" }}
  {{- end }}
  {{- if eq $name "notification-service" }}
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  {{- end }}
  {{- range $key, $val := $app.extraEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- end }}
